### PR TITLE
Implement configuration for babel, sass, and eslint

### PR DESCRIPTION
**Pull request by jdcrensh**
This adds a few common configurations to Webpack:

* ES2015+ Javascript w/ Babel
* ~~[Babel Polyfill](https://babeljs.io/docs/usage/polyfill/)~~
* Sass w/ [PostCSS](https://github.com/postcss/postcss)
* ~~ESLint~~
* ~~JSX (optional, React is not included)~~
* ~~Importing of JSON objects (json-loader)~~
* ~~Importing of images and/or fonts; ie. glyphicons, font-awesome, etc. (file-loader)~~

Built using `npm run build` and outputs to root directory (index.html, bundle.js).
* ~~Minification ON: `export NODE_ENV=production && npm run build`~~
* ~~Minification OFF: `export NODE_ENV=development && npm run build`~~

#1

### CODE REVIEW

**Comment by limonte** [comment]
Hi @jdcrensh!

Your PR is technically perfect, but as to me we shouldn't merge it. 

First reason is that after merging this PR, the live demo https://limonte.github.io/sweetalert2-webpack-demo/ won't work anymore, because there's no index.html and bundle.js in the repo.

Second and most important reason is that the purpose of this repo is not to be technically perfect, maintainable, modern, testable or cool. The purpose is to just show the simplest possible way to use swal2 with webpack.

[How it feels to learn JavaScript in 2016?](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f#.ox0t6qdek)

For Christ's sake, why should I have to add 20+ dev deps just to show the modal window? Personally, I don't like the way JS is going today :( 
   
```js
 +    "babel": "^6.5.2",
 +    "babel-loader": "^6.2.5",
 +    "babel-plugin-add-module-exports": "^0.2.1",
 +    "babel-polyfill": "^6.16.0",
 +    "babel-preset-es2015": "^6.16.0",
 +    "babel-preset-react": "^6.16.0",
 +    "babel-preset-stage-0": "^6.16.0",
 +    "clean-webpack-plugin": "^0.1.11",
 +    "css-loader": "^0.25.0",
 +    "eslint": "^3.7.1",
 +    "eslint-config-airbnb": "^12.0.0",
 +    "eslint-import-resolver-webpack": "^0.6.0",
 +    "eslint-plugin-import": "^1.16.0",
 +    "eslint-plugin-jsx-a11y": "^2.2.2",
 +    "eslint-plugin-react": "^6.3.0",
 +    "file-loader": "^0.9.0",
 +    "html-webpack-plugin": "^2.22.0",
 +    "imports-loader": "^0.6.5",
 +    "json-loader": "^0.5.4",
 +    "node-sass": "^3.10.1",
 +    "postcss-loader": "^0.13.0",
 +    "sass-loader": "^4.0.2",
 +    "style-loader": "^0.13.1",
 +    "webpack": "^2.1.0-beta.25"
```

**Comment by jdcrensh** [comment]
I get where you're coming from. I think we can strip out a good chunk of the stuff, while leaving the Babel and Sass loaders. I'll update.

**Comment by limonte** [comment]
Yeah, that will be great! :+1: I'd like to see the simplified version of this PR.

**Comment by jdcrensh** [comment]
I removed everything except for Babel dependencies, Sass/PostCSS loaders and their dependencies, and html-webpack-plugin for generating the `index.html`.

**Comment by limonte** [comment]
**AWESOME!** 

This is exactly what I wanted to see! Thanks a lot, Jon, for updating the PR and making it perfect. :beers:

**Pull request merged**
